version: '3.0'

services:
  server:
    image: 'nginx'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    links:
      - 'web1'
      - 'web2'
      - 'web3'
    ports:
      - '4000:4000'

  web1:
    build:
      context: '.'
      dockerfile: 'Dockerfile.web'
    volumes:
      - '.:/app'
    ports:
      - '8080'
    links:
      - 'redis'
    depends_on:
      - 'dict'
    environment:
      - 'SERVER_NO=1'

  web2:
    build:
      context: '.'
      dockerfile: 'Dockerfile.web'
    volumes:
      - '.:/app'
    ports:
      - '8080'
    links:
      - 'redis'
    depends_on:
      - 'dict'
    environment:
      - 'SERVER_NO=2'

  web3:
    build:
      context: '.'
      dockerfile: 'Dockerfile.web'
    volumes:
      - '.:/app'
    ports:
      - '8080'
    links:
      - 'redis'
    depends_on:
      - 'dict'
    environment:
      - 'SERVER_NO=3'

  dict:
    build:
      context: '.'
      dockerfile: 'Dockerfile.dict'
    volumes:
      - '.:/app'
    links:
      - 'redis'

  redis:
    image: 'redis'
