version: '2'

services:
  lb:
    image: 'dockercloud/haproxy'
    links:
      - 'web'
    ports:
      - '4000:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  web:
    build: '.'
    volumes:
      - '.:/app'
    links:
      - 'redis:redis'
    ports:
      - '8080'
    entrypoint: 'node server.js'

  dict:
    build: '.'
    volumes:
      - '.:/app'
    links:
      - 'redis:redis'
    entrypoint: 'node markov.js'

  redis:
    image: 'redis'
